name: Docs Lint Reusable Workflow

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Markdown
        uses: davidB/markdown-lint@v2.0
        with:
          args: "**/*.md"
          
      - name: Check generated links
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          # Check all markdown files in root and subdirectories
          args: --accept=200,204,429 --exclude-loopback "**/*.md"
